name: Test
on:
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  read-all:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: gh token-info scopes ${{ secrets.GITHUB_TOKEN }}
      - run: gh token-info user ${{ secrets.GITHUB_TOKEN }}

  write-all:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: gh token-info scopes ${{ secrets.GITHUB_TOKEN }}
      - run: gh token-info user ${{ secrets.GITHUB_TOKEN }}
